# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.5.0

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-05-29T16:37:06Z"
  labels:
    app: vibrantbassi-pod
  name: vibrantbassi-pod
spec:
  ports:
  - name: "3306"
    nodePort: 31666
    port: 3306
    targetPort: 3306
  - name: "8080"
    nodePort: 31093
    port: 8080
    targetPort: 8080
  selector:
    app: vibrantbassi-pod
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.podman.annotations.ulimit: nofile=524288:524288,nproc=127618:127618
    org.opencontainers.image.base.digest/lovingdirac: sha256:a33d71b6c2bbd1397b1e906c3f7df0a645477d7249f1f034513f1cf4
    org.opencontainers.image.base.digest/vibrantbassi: sha256:13e429971e970ebcb7bc611de52d71a3c444247dc67cf7475a02718f
    org.opencontainers.image.base.name/lovingdirac: docker.io/library/golang:1.20-buster
    org.opencontainers.image.base.name/vibrantbassi: docker.io/library/mysql:latest
  creationTimestamp: "2023-05-29T16:37:06Z"
  labels:
    app: vibrantbassi-pod
  name: vibrantbassi-pod
spec:
  containers:
  - args:
    - mysqld
    - --init-file=/tmp/create-local-db.sql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: pass
    image: localhost/mysql-container:latest
    name: vibrantbassi
    ports:
    - containerPort: 3306
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: a196758d08199bd7200bf0e6f6f89fe1a6c89e92336aa6a8d7e3d79ec49d2576-pvc
  - image: localhost/golang-container:latest
    name: lovingdirac
    ports:
    - containerPort: 8080
  volumes:
  - name: a196758d08199bd7200bf0e6f6f89fe1a6c89e92336aa6a8d7e3d79ec49d2576-pvc
    persistentVolumeClaim:
      claimName: a196758d08199bd7200bf0e6f6f89fe1a6c89e92336aa6a8d7e3d79ec49d2576
