# Use the official golang image to create a mysql instance.
# https://hub.docker.com/_/golang
FROM mysql

# Copy the database definition to a temporal directory.
COPY ./create-local-db.sql /tmp

# Expose the port used by the mysql instance.
EXPOSE 3306

# Run the mysql server executable and read the database
# definition file at startup.
CMD ["mysqld", "--init-file=/tmp/create-local-db.sql"]